spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauthdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: test

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
